### ISSUE TITLE
Initial version TODO

### ISSUE THREAD

**Issue by benkeen** [IMERSS/inat-components#1]
High-level TODO to get the first version out the door. 

- [x] Year option with stats page
- [x] Make stats page responsive
- [x] Make tabs responsive
- [x] generating all JSON data files
- [x] setup server with cron
- [x] move to monorepo/Nx? Need standalone build for BC Leps for starters.
- [x] Export all available components
- [x] Publish to npm 
- [x] Documentation - at least a first pass
- [x] Error handling for failed requests
